# Generated by Django 4.0.6 on 2022-11-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rfid_uid',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
