# Generated by Django 4.0.6 on 2022-11-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanager', '0002_student_rfid_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10)),
                ('device_manufacturer', models.CharField(max_length=20)),
                ('device_name', models.CharField(max_length=20)),
                ('room_number', models.IntegerField()),
                ('hall', models.CharField(choices=[('Lupton', 'Lupton'), ('Gleeson', 'Gleeson'), ('Whitmann', 'Whitmann')], default='Lupton', max_length=10)),
            ],
        ),
    ]
