# Generated by Django 4.0.6 on 2022-11-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanager', '0003_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='uniquekeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unikey', models.CharField(max_length=20)),
            ],
        ),
    ]
