# Generated by Django 4.0.6 on 2023-02-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanager', '0004_uniquekeys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='uniquekeys',
        ),
    ]
