# Generated by Django 4.0.6 on 2023-03-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanager', '0005_delete_uniquekeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('dev_id', models.CharField(max_length=20)),
                ('ram_id', models.CharField(max_length=20)),
                ('room_number', models.IntegerField()),
                ('hall', models.CharField(max_length=10)),
                ('timeoflogin', models.TimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourcemanager.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourcemanager.student')),
            ],
        ),
        migrations.CreateModel(
            name='Allowed_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourcemanager.student')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='allowed_users',
            field=models.ManyToManyField(to='resourcemanager.allowed_users'),
        ),
    ]
