# Generated by Django 4.0.6 on 2023-04-03 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanager', '0007_alter_device_logs_timeoflogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_logs',
            name='timeoflogin',
            field=models.TimeField(verbose_name=datetime.datetime(2023, 4, 3, 15, 52, 38, 81906)),
        ),
    ]
