# Generated by Django 4.0.6 on 2023-04-03 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanager', '0008_alter_device_logs_timeoflogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_logs',
            name='timeoflogin',
            field=models.TimeField(auto_now_add=True, verbose_name=datetime.datetime(2023, 4, 3, 15, 53, 37, 917208)),
        ),
    ]
