# Generated by Django 4.0.6 on 2023-04-03 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanager', '0010_device_logs_dateoflogin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_logs',
            name='dateoflogin',
            field=models.DateField(default=datetime.date(2023, 4, 3), verbose_name=datetime.date(2023, 4, 3)),
        ),
        migrations.AlterField(
            model_name='device_logs',
            name='timeoflogin',
            field=models.TimeField(auto_now_add=True, verbose_name=datetime.datetime(2023, 4, 3, 16, 15, 42, 989636)),
        ),
    ]
