# Generated by Django 4.0.6 on 2023-05-06 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanager', '0012_alter_device_logs_timeoflogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.CharField(max_length=20)),
                ('d_name', models.CharField(max_length=20)),
                ('d_hall', models.CharField(max_length=10)),
                ('d_room', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='device_logs',
            name='dateoflogin',
            field=models.DateField(default=datetime.date(2023, 5, 5), verbose_name=datetime.date(2023, 5, 5)),
        ),
        migrations.AlterField(
            model_name='device_logs',
            name='timeoflogin',
            field=models.TimeField(default=datetime.datetime(2023, 5, 5, 23, 1, 18, 492580)),
        ),
    ]
